<a href="https://colab.research.google.com/github/RazvanPorojan/metal_python/blob/master/Recruitment_Fee_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
from keras.models import model_from_json
import numpy

Using TensorFlow backend.


Load Data

In [2]:
data = pd.read_csv("target_calc.csv")
data.head()


deals_closed  good_cvs  signed_ndas  worked_jobs  payment
0           0.0       4.0          0.0          3.0     1.35
1           0.0       7.0          1.0          4.0     2.05
2           1.0      10.0          1.0          7.0     3.35
3           2.0      20.0          2.0         10.0     5.50
4           3.0      20.0          2.0         10.0     6.50

In [3]:
data.dtypes

deals_closed    float64
good_cvs        float64
signed_ndas     float64
worked_jobs     float64
payment         float64
dtype: object

Define Keras Model

In [32]:
#model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[4])])
#model.compile(optimizer='sgd', loss='mean_squared_error')

model = tf.keras.Sequential()

model.add(keras.layers.Dense(1, input_dim=4, activation='linear'))
#model.add(keras.layers.Dense(1, kernel_initializer='normal'))

sgd = tf.keras.optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
#sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)



# Compile model
model.compile(loss='mean_squared_error', optimizer="adam" , metrics=['accuracy'])
print(model.summary())


Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 1)                 5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
None


Define input and output

In [5]:
xs = data[["deals_closed","good_cvs","signed_ndas","worked_jobs"]].to_numpy()
ys = data[["payment"]].to_numpy()
print(xs)
print("---")
print(ys)

[[ 0.  4.  0.  3.]
 [ 0.  7.  1.  4.]
 [ 1. 10.  1.  7.]
 [ 2. 20.  2. 10.]
 [ 3. 20.  2. 10.]
 [ 4. 20.  4. 10.]
 [ 5. 22.  4. 10.]
 [ 1. 20.  4. 10.]
 [ 3. 30.  4. 10.]]
---
[[1.35]
 [2.05]
 [3.35]
 [5.5 ]
 [6.5 ]
 [8.5 ]
 [9.6 ]
 [5.5 ]
 [8.  ]]


Train Model

In [44]:
model.fit(xs, ys, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 920us/step - loss: 6.3159e-15 - accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 4.0605e-07 - accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 0s 1ms/step - loss: 1.4670e-06 - accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 2.9839e-06 - accuracy: 0.0000e+00
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 4.8089e-06 - accuracy: 0.0000e+00
Epoch 6/10
1/1 [==============================] - 0s 3ms/step - loss: 6.8219e-06 - accuracy: 0.0000e+00
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 8.9348e-06 - accuracy: 0.0000e+00
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 1.1079e-05 - accuracy: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 1.3207e-05 - accuracy: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 2ms/step

In [45]:
model.get_weights()

[array([[1.0021267 ],
        [0.04877639],
        [0.5009672 ],
        [0.05149108]], dtype=float32), array([1.0023072], dtype=float32)]

Load Weights

In [0]:
ideal = [np.array([[ 1.0  ],
        [0.05],
        [ 0.5],
        [ 0.05]], dtype="float32"), np.array([1.0], dtype="float32")]
model.set_weights(ideal)

In [42]:
print(model.predict([[ 0.0,4.0,0.0,3.0]])) #1.35
print(model.predict([[ 0.0,7.0,1.0,4.0]])) #2.05
print(model.predict([[ 1.0,10.0,1.0,7.0]])) #3.35
print(model.predict([[ 2.0,20.0,2.0,10.0]])) #5.5
print(model.predict([[ 4.0,20.0,4.0,10.0]])) #8.5
print(model.predict([[ 3.0,30.0,4.0,10.0]])) #8

[[1.35]]
[[2.0500002]]
[[3.35]]
[[5.5]]
[[8.5]]
[[8.]]
