<a href="https://colab.research.google.com/github/RazvanPorojan/metal_python/blob/master/Recruitment_Fee_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [0]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd


Load Data

In [2]:
data = pd.read_csv("target_calc.csv")
data.head()


deals_closed  good_cvs  signed_ndas  worked_jobs  payment
0           0.0       4.0          0.0          3.0     1.35
1           0.0       7.0          1.0          4.0     2.05
2           1.0      10.0          1.0          7.0     3.35
3           2.0      20.0          2.0         10.0     5.50
4           3.0      20.0          2.0         10.0     6.50

In [3]:
data.dtypes

deals_closed    float64
good_cvs        float64
signed_ndas     float64
worked_jobs     float64
payment         float64
dtype: object

Define Keras Model

In [4]:
#model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[4])])
#model.compile(optimizer='sgd', loss='mean_squared_error')

model = tf.keras.Sequential()
model.add(keras.layers.Dense(1, input_dim=4, kernel_initializer='normal'))
#model.add(keras.layers.Dense(1, kernel_initializer='normal'))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
None


Define input and output

In [5]:
xs = data[["deals_closed","good_cvs","signed_ndas","worked_jobs"]].to_numpy()
ys = data[["payment"]].to_numpy()
print(xs)
print("---")
print(ys)

[[ 0.  4.  0.  3.]
 [ 0.  7.  1.  4.]
 [ 1. 10.  1.  7.]
 [ 2. 20.  2. 10.]
 [ 3. 20.  2. 10.]
 [ 4. 20.  4. 10.]
 [ 5. 22.  4. 10.]
 [ 1. 20.  4. 10.]
 [ 3. 30.  4. 10.]]
---
[[1.35]
 [2.05]
 [3.35]
 [5.5 ]
 [6.5 ]
 [8.5 ]
 [9.6 ]
 [5.5 ]
 [8.  ]]


Train Model

In [6]:
model.fit(xs, ys, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 2ms/step - loss: 34.5618
Epoch 2/2000
1/1 [==============================] - 0s 1ms/step - loss: 34.1767
Epoch 3/2000
1/1 [==============================] - 0s 2ms/step - loss: 33.7938
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 33.4133
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 33.0351
Epoch 6/2000
1/1 [==============================] - 0s 1ms/step - loss: 32.6594
Epoch 7/2000
1/1 [==============================] - 0s 2ms/step - loss: 32.2861
Epoch 8/2000
1/1 [==============================] - 0s 1ms/step - loss: 31.9152
Epoch 9/2000
1/1 [==============================] - 0s 1ms/step - loss: 31.5469
Epoch 10/2000
1/1 [==============================] - 0s 2ms/step - loss: 31.1811
Epoch 11/2000
1/1 [==============================] - 0s 1ms/step - loss: 30.8179
Epoch 12/2000
1/1 [==============================] - 0s 2ms/step - loss: 30.4573
Epoch 13/2000
1/1 [==================

In [7]:
model.get_weights()

[array([[0.5560872 ],
        [0.14578006],
        [0.19939464],
        [0.16183259]], dtype=float32), array([0.11633953], dtype=float32)]

In [8]:
print(model.predict([[ 0.0,4.0,0.0,3.0]])) #1.35
print(model.predict([[ 0.0,7.0,1.0,4.0]])) #2.05
print(model.predict([[ 1.0,10.0,1.0,7.0]])) #3.35
print(model.predict([[ 2.0,20.0,2.0,10.0]])) #5.5
print(model.predict([[ 4.0,20.0,4.0,10.0]])) #8.5
print(model.predict([[ 3.0,30.0,4.0,10.0]])) #8

[[1.1849576]]
[[1.9835249]]
[[3.4624503]]
[[6.1612306]]
[[7.672194]]
[[8.573908]]
